# Generated by Django 4.2.26 on 2025-11-24 07:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('include_breakfast', models.BooleanField(default=True)),
                ('breakfast_weight', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_messes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.mess')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mess', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MealManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('week', 'Week-based'), ('days', 'Day-based'), ('custom', 'Custom')], max_length=10)),
                ('period_choice', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('manager_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assignments', to='core.member')),
                ('manager_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='core.mess')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('rice', 'Rice'), ('meat', 'Meat'), ('veg', 'Vegetables'), ('fish', 'Fish'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.mess')),
                ('paid_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.member')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.mess')),
            ],
        ),
        migrations.CreateModel(
            name='MessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Meal Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.mess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mess', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('had_breakfast', models.BooleanField(default=False)),
                ('had_lunch', models.BooleanField(default=False)),
                ('had_dinner', models.BooleanField(default=False)),
                ('extra_meals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.member')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.mess')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('mess', 'member', 'date')},
            },
        ),
    ]
