# Generated by Django 4.2.26 on 2025-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_meal_pattern',
            field=models.CharField(choices=[('NONE', 'No default'), ('B', 'Breakfast only'), ('L', 'Lunch only'), ('D', 'Dinner only'), ('BL', 'Breakfast + Lunch'), ('LD', 'Lunch + Dinner'), ('BD', 'Breakfast + Dinner'), ('BLD', 'Breakfast + Lunch + Dinner')], default='NONE', max_length=10),
        ),
    ]
